# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3cc3209305f34b13b9afd39677ab8cda7403dc3b0e5998993e14e40ce9da053d024ab52db08cdcc4fb75a8e1e00172353931a2e4717c6e62785dfb24f5678b3

test:
  secret_key_base: 16c454fbc526c795d8b9da4541c994b8d163914c64304e54f62bd59b6f0adff6bd9e0cb304a294310a07158df4722fbaf1522e49e9d284d04753436bae2572ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
